Cats99/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      patch "deny"
      patch "approve"
    end

  end

end

Cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :datetime         not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base
  COLORS = ["white", "black", "purple"]
  SEXES = %w(m f)

  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: SEXES }

  has_many :cat_rental_requests, :dependent => :destroy

  def age
    Time.now.year - birth_date.year
  end
end

Cats99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :datetime         not null
#  end_date   :datetime         not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ActiveRecord::Base
  STATUSES = %w(PENDING APPROVED DENIED)
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: {in: STATUSES}
  validate  :no_overlapping_approved_requests
  validate :start_date_precedes_end_date
  belongs_to :cat

  def approve!
    return unless pending?
    CatRentalRequest.transaction do
      overlapping_requests.update_all(status: "DENIED")
      self.update(status: "APPROVED")
    end
  end

  def deny!
    self.update(status: "DENIED")
  end

  def pending?
    status == 'PENDING'
  end

  private
  def overlapping_requests
    @cat_rental_requests = CatRentalRequest.where(cat_id: cat_id)
        .where("start_date BETWEEN '#{start_date}' AND '#{end_date}' OR
                end_date BETWEEN '#{start_date}' AND '#{end_date}'")

  end

  def no_overlapping_approved_requests
    overlap = overlapping_requests.where(status: "APPROVED")
    unless overlap.empty?
      errors.add(:overlap, "cannot have overlapping requests")
    end
  end

 def start_date_precedes_end_date
    if start_date > end_date
      errors.add(:bad_date, "Cannot start after you end")
    end
  end
end

Cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    render :new
  end

  def show
    @request = CatRentalRequest.find(params[:id])
    render :show
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.save
      redirect_to cat_rental_request_path(@request)
    else
      # @cats = Cat.all
      render :new
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_path(@request.cat_id)
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_path(@request.cat_id)
  end

  private
  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end

end

Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    # @cat = Cat.includes(:cat_rental_requests).find(params[:id])
    @cat = Cat.find(params[:id])
    @requests = @cat.cat_rental_requests.order(:start_date)
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      redirect_to new_cat_url
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_path(@cat)
    else
      redirect_to edit_cat_path(@cat)
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_path
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
  end
end

Cats99/app/views/cat_rental_requests/new.html.erb
<h1>Create a Rental Request</h1>

<form class="" action="/cat_rental_requests" method="post">
    <label>Cat:</label>
    <br>
    <select name="cat_rental_request[cat_id]">
       <% @cats.each do |cat| %>
        <option value=<%= cat.id %> >
          <%= cat.name %>
        </option>
       <%end %>
     </select>
     <br>

     <label>Start Date:</label>
     <br>
     <input type="date"
            name="cat_rental_request[start_date]"
            value=<%= Time.now %>>
     <br>

     <label>End Date:</label>
     <br>
     <input type="date"
            name="cat_rental_request[end_date]"
            value=<%= Time.now + 3.days %>>
     <br>

    <input type="submit">
</form>

Cats99/app/views/cat_rental_requests/show.html.erb
<h1>Cat request #<%= @request.id %></h1>

<table>
  <tr>
    <td><strong>Cat Name</strong></td>
    <td><%=  @request.cat.name %></td>
  </tr>
  <tr>
    <td><strong>Start Date</strong></td>
    <td><%= @request.start_date %></td>
  </tr>
  <tr>
    <td><strong>End Date</strong></td>
    <td><%= @request.end_date %></td>
  </tr>
  <tr>
    <td><strong>Status</td></strong>
    <td><%= @request.status.downcase.capitalize %></td>
  </tr>
</table>

Cats99/app/views/cats/_form.html.erb
  <label>Name:</label>
  <input type="text" name="cat[name]" value=<%= cat.name %>>
  <br>

  <label>Sex:</label>
  <input type="radio" name="cat[sex]" value="m" <%= 'checked 'if cat.sex == "m"%>>Male
  <input type="radio" name="cat[sex]" value="f"<%='checked ' if cat.sex == "f"%>>Female
  <br>

  <label>Color:</label>
  <br>
  <select name="cat[color]">
     <% ["",'white','black','purple'].each do |color| %>
      <option value=<%= color %> <%= "selected=\"selected\"" if cat.color == color %>>
        <%= color %>
      </option>
     <%end %>
   </select>
   <br>

   <label>Birth Date:</label>
   <br>
   <input type="date" name="cat[birth_date]" value=<%= cat.birth_date %>>
   <br>

   <label>Description:</label>
   <br>
   <textarea name="cat[description]" rows="5" cols= "50"><%= cat.description %></textarea>

   <br>
  <input type="submit">

Cats99/app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %></h1>

<form action="<%= cat_url(@cat) %>" method="post">
<input type="hidden" name="_method" value="patch">
  <%= render 'form', cat: @cat %>
</form>

Cats99/app/views/cats/index.html.erb
<h1>All Cats</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Age</th>
    <th>Description</th>
  </tr>
  <% @cats.each do |cat| %>
    <tr>
      <td><%= link_to cat.name, cat_path(cat.id) %></td>
      <td><%= cat.color %></td>
      <td><%= cat.sex %></td>
      <td><%= cat.age %></td>
      <td><%= cat.description %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "Create a new Cat", new_cat_path %>

Cats99/app/views/cats/new.html.erb
<h1>New Cat</h1>

<form action="/cats" method="post">
  <%= render 'form', cat: @cat %>
</form>

Cats99/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<%= link_to "Edit", edit_cat_path(@cat) %>
<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Age</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<h2>Requests</h2>
<table>
    <tr>
      <th>id</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
    </tr>
  <% @requests.each do |request|%>
      <tr>
        <td><%= request.id %></td>
        <td> <%= request.start_date %> </td>
        <td> <%= request.end_date %></td>
        <td> <%=  request.status %></td>
        <% if request.pending? %>
          <td>
            <%= button_to "Approve Request",
              approve_cat_rental_request_url(request),
              method: :patch %>
          </td>
          <td> <%= button_to "Deny Request", {controller: "cat_rental_requests",
                        action: "deny", id: request.id}, {method: :patch}%> </td>
        <% end %>
      </tr>
  <% end %>
</table>

<%= link_to "Index", cats_path %>
<%= button_to "Delete Cat", { action: "destroy", id: @cat.id },
                                method: :delete, data: { confirm: "Are you sure?" } %>

Cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>